name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and cache node modules
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set SHAs for affected packages
        uses: nrwl/nx-set-shas@v4

      - name: Print Environment Information
        run: npx nx report

      - name: Lint, test, and build affected packages
        run: npx nx affected -t lint,test,build

      - name: Publish packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
          NPM_CONFIG_PROVENANCE: true