name: Visual Regression Tests

on: 
    push:
        branches: 
          - main 
    pull_request:
        branches:
          - main

jobs:
    visual-tests:
        runs-on: ubuntu-latest

        steps: 
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with: 
            node-version: 20
            cache: "npm"

        - name: Install Root Dependencies
          run: npm install

        - name: Install Playwright browsers in frontend-ui
          run: npx playwright install --with-deps

        - name: Building the application
          run: npm run build

        - name: Start the Alpha-app for testing in the background
          run: npm run start &
          working-directory: packages/alpha-app

        - name: Wait for Alpha-app to be ready
          run: npx wait-on http://localhost:3000

        - name: Run visual regression test updates
          run: npm run test:visual:update
          working-directory: packages/frontend-ui

        - name: Run visual regression tests
          run: npm run test:visual
          working-directory: packages/frontend-ui